[project]
name = "triton-inference-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "triton>=3.6.0",
    "tritonclient>=2.65.0",
    "ultralytics>=8.4.14",
]
